services:
  permission-db:
    image: postgres:16
    container_name: permission-db
    environment:
      POSTGRES_DB: permission_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d permission_db"]
      interval: 5s
      timeout: 3s
      retries: 15
    ports:
      - "5436:5432"
    networks: [ss-dev]

  permission-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: permission-service
    environment:
      DB_HOST: permission-db
      DB_PORT: 5432
      DB_NAME: permission_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      AUTH0_ISSUER: https://dev-7t5evioih4aq30t7.us.auth0.com/
      AUTH0_AUDIENCE: https://snippet-api
    depends_on:
      permission-db:
        condition: service_healthy
    ports:
      - "8083:8080"
    networks: [ss-dev]

networks:
  ss-dev:
    external: true
